import * as fs from "fs";
import * as path from "path";

interface ColorValue {
  r: number;
  g: number;
  b: number;
  a: number;
}

interface VariableAlias {
  type: "VARIABLE_ALIAS";
  id: string;
}

type ModeValue = ColorValue | VariableAlias | number;

interface Variable {
  id: string;
  name: string;
  resolvedType: "COLOR" | "FLOAT";
  valuesByMode: Record<string, ModeValue>;
  variableCollectionId: string;
}

interface Mode {
  name: string;
  modeId: string;
}

interface Collection {
  id: string;
  name: string;
  defaultModeId: string;
  modes: Mode[];
  variables: Variable[];
}

interface TokenFile {
  collections: Collection[];
}

function rgbaToHex(c: ColorValue): string {
  const r = Math.round(c.r * 255);
  const g = Math.round(c.g * 255);
  const b = Math.round(c.b * 255);
  if (c.a !== undefined && c.a < 1) {
    const a = Math.round(c.a * 255);
    return `#${r.toString(16).padStart(2, "0")}${g.toString(16).padStart(2, "0")}${b.toString(16).padStart(2, "0")}${a.toString(16).padStart(2, "0")}`;
  }
  return `#${r.toString(16).padStart(2, "0")}${g.toString(16).padStart(2, "0")}${b.toString(16).padStart(2, "0")}`;
}

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/\//g, "-")
    .replace(/\s+/g, "-")
    .replace(/_/g, "-")
    .replace(/--+/g, "-");
}

function radiusSlug(name: string): string {
  return name.replace(/^border-radius-/, "").toLowerCase();
}

const tokensPath = path.resolve(__dirname, "../src/design/tokens.json");
const data: TokenFile = JSON.parse(fs.readFileSync(tokensPath, "utf-8"));

const variableMap = new Map<string, Variable>();
const collectionMap = new Map<string, Collection>();

for (const collection of data.collections) {
  collectionMap.set(collection.id, collection);
  for (const variable of collection.variables) {
    variableMap.set(variable.id, variable);
  }
}

function resolveValue(
  variable: Variable,
  modeId: string,
): string | number | null {
  const value = variable.valuesByMode[modeId];
  if (value === undefined || value === null) return null;

  if (
    typeof value === "object" &&
    "type" in value &&
    value.type === "VARIABLE_ALIAS"
  ) {
    const referenced = variableMap.get(value.id);
    if (!referenced) return null;
    const refCollection = collectionMap.get(referenced.variableCollectionId);
    if (!refCollection) return null;
    return resolveValue(referenced, refCollection.defaultModeId);
  }

  if (variable.resolvedType === "COLOR") {
    return rgbaToHex(value as ColorValue);
  }

  return value as number;
}

// ──────────────────────────────────────────────
// 1. tokens.css: raw CSS custom properties
// ──────────────────────────────────────────────

const primitiveVars: string[] = [];
const lightVars: string[] = [];
const darkVars: string[] = [];

for (const collection of data.collections) {
  if (collection.name === "Theme") {
    const lightModeId = collection.modes.find(
      (m) => m.name === "Light",
    )?.modeId;
    const darkModeId = collection.modes.find(
      (m) => m.name === "Dark",
    )?.modeId;
    if (!lightModeId || !darkModeId) continue;

    for (const variable of collection.variables) {
      const slug = slugify(variable.name);
      const lightVal = resolveValue(variable, lightModeId);
      const darkVal = resolveValue(variable, darkModeId);
      if (lightVal !== null)
        lightVars.push(`  --theme-${slug}: ${lightVal};`);
      if (darkVal !== null) darkVars.push(`  --theme-${slug}: ${darkVal};`);
    }
  } else if (collection.name !== "Breakpoint") {
    const modeId = collection.defaultModeId;

    for (const variable of collection.variables) {
      const val = resolveValue(variable, modeId);
      if (val === null) continue;

      let varName: string;
      if (collection.name === "Shape/Radius") {
        varName = `radius-${radiusSlug(variable.name)}`;
      } else {
        const prefix = slugify(collection.name);
        varName = `${prefix}-${slugify(variable.name)}`;
      }

      const cssVal = typeof val === "number" ? `${val}px` : val;
      primitiveVars.push(`  --${varName}: ${cssVal};`);
    }
  }
}

const tokensCss = `/* AUTO-GENERATED by scripts/generate-tailwind-theme.ts */
/* Source: src/design/tokens.json (exported from Figma Variable Visualizer) */
/* DO NOT EDIT MANUALLY. Re-run: npm run sync-tokens */

@layer base {
  :root {
    /* ═══ Primitive tokens ═══ */
${primitiveVars.join("\n")}

    /* ═══ Semantic tokens (Light mode, default) ═══ */
${lightVars.join("\n")}
  }

  .dark,
  [data-theme="dark"] {
    /* ═══ Semantic tokens (Dark mode) ═══ */
${darkVars.join("\n")}
  }
}
`;

// ──────────────────────────────────────────────
// 2. theme.css: Tailwind v4 @theme registration
// ──────────────────────────────────────────────

const colorCollection = data.collections.find((c) => c.name === "Color");
const spacingCollection = data.collections.find((c) => c.name === "Spacing");
const radiusCollection = data.collections.find(
  (c) => c.name === "Shape/Radius",
);
const breakpointCollection = data.collections.find(
  (c) => c.name === "Breakpoint",
);
const themeCollection = data.collections.find((c) => c.name === "Theme");

const themeLines: string[] = [];

themeLines.push("  /* ═══ Primitive colors ═══ */");
if (colorCollection) {
  for (const v of colorCollection.variables) {
    const slug = slugify(v.name);
    themeLines.push(`  --color-${slug}: var(--color-${slug});`);
  }
}

themeLines.push("");
themeLines.push("  /* ═══ Semantic colors (switch with .dark) ═══ */");
if (themeCollection) {
  for (const v of themeCollection.variables) {
    const slug = slugify(v.name);
    themeLines.push(`  --color-${slug}: var(--theme-${slug});`);
  }
}

themeLines.push("");
themeLines.push("  /* ═══ Spacing ═══ */");
if (spacingCollection) {
  for (const v of spacingCollection.variables) {
    const slug = slugify(v.name);
    themeLines.push(`  --spacing-${slug}: var(--spacing-${slug});`);
  }
}

themeLines.push("");
themeLines.push("  /* ═══ Border Radius ═══ */");
if (radiusCollection) {
  for (const v of radiusCollection.variables) {
    const slug = radiusSlug(v.name);
    themeLines.push(`  --radius-${slug}: var(--radius-${slug});`);
  }
}

themeLines.push("");
themeLines.push("  /* ═══ Breakpoints ═══ */");
if (breakpointCollection) {
  for (const v of breakpointCollection.variables) {
    const val = resolveValue(v, breakpointCollection.defaultModeId);
    if (val !== null) {
      themeLines.push(`  --breakpoint-${v.name}: ${val}px;`);
    }
  }
}

const themeCss = `/* AUTO-GENERATED by scripts/generate-tailwind-theme.ts */
/* Tailwind v4 @theme registration of Figma design tokens */
/* DO NOT EDIT MANUALLY. Re-run: npm run sync-tokens */

@theme inline {
${themeLines.join("\n")}
}
`;

// ──────────────────────────────────────────────
// 3. Write files
// ──────────────────────────────────────────────

const tokensCssPath = path.resolve(__dirname, "../src/design/tokens.css");
const themeCssPath = path.resolve(__dirname, "../src/design/theme.css");

fs.writeFileSync(tokensCssPath, tokensCss);
fs.writeFileSync(themeCssPath, themeCss);

// Clean up old tailwind-tokens.ts if it exists
const oldTsPath = path.resolve(__dirname, "../src/design/tailwind-tokens.ts");
if (fs.existsSync(oldTsPath)) fs.unlinkSync(oldTsPath);

const colorCount = colorCollection?.variables.length ?? 0;
const themeVarCount = themeCollection?.variables.length ?? 0;
const spacingCount = spacingCollection?.variables.length ?? 0;
const radiusCount = radiusCollection?.variables.length ?? 0;
const bpCount = breakpointCollection?.variables.length ?? 0;

console.log(`Generated:`);
console.log(`  ${tokensCssPath} (CSS custom properties)`);
console.log(`  ${themeCssPath} (Tailwind v4 @theme block)`);
console.log(
  `  ${colorCount} colors, ${themeVarCount} theme tokens, ${spacingCount} spacing, ${radiusCount} radius, ${bpCount} breakpoints`,
);
